# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 04:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='static/pictures/images')),
                ('time', models.DateTimeField(default=datetime.datetime(2016, 12, 1, 4, 1, 26, 136471, tzinfo=utc))),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='picture_people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=20)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.Picture')),
            ],
        ),
        migrations.CreateModel(
            name='picture_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.Picture')),
            ],
        ),
    ]
